version: '3'
services: 
  api:
    container_name: connected-vehicle-api
    build: .
    command: node app.js
    restart: always
    ports: 
      - "8080:8080"
    depends_on:
      - "mongo"
    links:
      - mongo
    environment:
      NODE_ENV: 'docker' 
  test:
    container_name: connected-vehicle-test
    build: .
    command: ["npm", "test"]
    ports: 
      - "8080:8080"
    depends_on:
      - "mongo"
    links:
      - mongo
    environment:
      NODE_ENV: docker
  mongo:
    image: "mongo"
    container_name: mongo
    ports:
      - "27018:27017"